import requests
import crypto_backend
import os
import json
import encrypted_messenger
url = 'http://cs448lnx101.gcc.edu/posts/view/608' #658 is a fake generated by tmp2.py

# r = open('Accounts/Tommy.txt', 'r')
# tom = json.loads(r.readline())
# tom = encrypted_messenger.KeyringEntry(crypto_backend.rsa_deserialize_private_key(tom['private_key']), tom['owner'], tom['id'])
# r.close()

c = open('System/contacts.txt', 'r')
contacts = [encrypted_messenger.JSONKeyring(contact) for contact in json.load(c)]
c.close()

sender = ""
for contact in contacts:
    if contact.owner == 'TEST#1':
        sender = contact
        break


message = requests.get(url).json()['contents'][7:]
message = json.loads(message)
key = encrypted_messenger.b64decode(message['sessionkey'], validate=True)
nonce = encrypted_messenger.b64decode(message['nonce'], validate=True)
text = encrypted_messenger.b64decode(message['ciphertext'], validate=True)
m = key+nonce+text
print(crypto_backend.verify_signature(sender.public, m, encrypted_messenger.b64decode(message['signature'], validate=True)))